spring:
  application:
    name: social-media
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    user: sa
    password: password
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
